import { IsString, IsNotEmpty, IsOptional, IsUUID } from 'class-validator';

// Username and password are generated by the server.
export class CreateStudentDto {
  @IsString()
  @IsNotEmpty()
  firstName: string;

  @IsString()
  @IsNotEmpty()
  lastName: string;

  @IsUUID()
  @IsNotEmpty()
  classId: string;

  @IsUUID()
  @IsOptional()
  departmentId?: string;
}
